### ISSUE TITLE
LZString throws w is undefined exception

### ISSUE THREAD

**Issue by SISheogorath** [pieroxy/lz-string#112]
We got some, not so nice, error messages out of LZString.

```
018-02-16T14:03:22.222Z - error:  TypeError: Cannot read property 'charAt' of undefined
at Object._decompress (/hackmd/node_modules/lz-string/libs/lz-string.js:473:24)
at Object.decompressFromBase64 (/hackmd/node_modules/lz-string/libs/lz-string.js:44:21)
```

Result:
---

```
LZString throws an `Cannot read property `charAt` of undefined
```

Expected result:
---

LZString returns an empty string as it usually does in case of invalid base64 strings.

Steps to reproduce:
---

1. Load LZString
2. Call `LZString.decompressFromBase64("zadachi")`

As comparsion:

1. Load LZString
2. Call `LZString.decompressFromBase64("asdf")`

**Comment by SISheogorath** [comment]
Related https://github.com/hackmdio/hackmd/issues/727
